# Generated by Django 3.2.7 on 2022-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0005_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_class',
            field=models.CharField(choices=[('I', 'First'), ('II', 'Second'), ('III', 'Third'), ('IV', 'Fourth'), ('V', 'Fifth'), ('VI', 'Sixth'), ('VII', 'Seventh'), ('VIII', 'Eigth'), ('IX', 'Ninth'), ('X', 'Tenth'), ('XI', 'Eleventh'), ('XII', 'Twelfth')], default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='test_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
