# Generated by Django 3.2.7 on 2022-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0007_alter_profile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
