# Generated by Django 3.2.7 on 2022-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0008_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='score',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
