# Generated by Django 4.0.1 on 2022-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0009_alter_profile_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='acontact',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
