# Generated by Django 4.0.1 on 2022-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0010_profile_acontact_profile_email_profile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='task1_image1',
            field=models.ImageField(default=1, upload_to='Task1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='task1_image2',
            field=models.ImageField(default=1, upload_to='Task1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='task1_image3',
            field=models.ImageField(default=1, upload_to='Task1'),
            preserve_default=False,
        ),
    ]
