# Generated by Django 4.0.1 on 2022-08-30 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0014_profile_insta_story'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_verified',
        ),
    ]
