# Generated by Django 4.0.1 on 2022-08-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0015_remove_profile_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image1',
            field=models.ImageField(blank=True, default=None, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, default=None, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, default=None, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_story',
            field=models.ImageField(blank=True, default=None, upload_to='Task2'),
        ),
    ]
