# Generated by Django 4.0.1 on 2022-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0016_alter_profile_image1_alter_profile_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_story',
            field=models.ImageField(blank=True, upload_to='Task2'),
        ),
    ]
