# Generated by Django 4.0.1 on 2022-09-03 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Login', '0017_alter_profile_image1_alter_profile_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='School_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('student_class', models.CharField(max_length=12)),
                ('school', models.CharField(max_length=30)),
                ('score', models.CharField(blank=True, max_length=12)),
                ('contact', models.CharField(max_length=12)),
                ('acontact', models.CharField(max_length=12)),
                ('country', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('image1', models.ImageField(blank=True, upload_to='Task1')),
                ('image2', models.ImageField(blank=True, upload_to='Task1')),
                ('image3', models.ImageField(blank=True, upload_to='Task1')),
                ('insta_story', models.ImageField(blank=True, upload_to='Task2')),
                ('is_qualified', models.BooleanField(default=False)),
                ('test_attempted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
