# Generated by Django 4.0.1 on 2022-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0018_school_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_profile',
            name='acontact',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='score',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='test_attempted',
        ),
        migrations.AddField(
            model_name='school_profile',
            name='landline_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_profile',
            name='mobile_number',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_profile',
            name='principal_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_profile',
            name='school_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_profile',
            name='school_strength',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_profile',
            name='teacher_incharge',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
