# Generated by Django 4.0.1 on 2022-09-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0019_remove_school_profile_acontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_profile',
            name='school_strength',
        ),
        migrations.AddField(
            model_name='school_profile',
            name='student_strength',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
