# Generated by Django 4.0.1 on 2022-09-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0020_remove_school_profile_school_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_profile',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
