# Generated by Django 4.0.1 on 2022-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0021_school_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_profile',
            name='student_strength',
            field=models.IntegerField(max_length=12),
        ),
    ]
