# Generated by Django 4.0.1 on 2022-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0022_alter_school_profile_student_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_profile',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='insta_story',
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Caring_for_Trees_After_Planting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Determine_Goals_for_Garden_and_gathering_of_materials',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Funding_and_Information_Sources',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Identification_assessment_and_planning_of_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Planning_for_setting_up_school_garden_and_Committee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Quiz_or_Olympiad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Selecting_and_Purchasing_Your_Trees',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Weekly_inspection_of_trees_for_disease_insects_or_vandalism',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school_profile',
            name='Written_permission_from_the_site_owner_and_gathering_of_materials',
            field=models.BooleanField(default=False),
        ),
    ]
