# Generated by Django 4.0.1 on 2022-09-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0023_remove_school_profile_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_profile',
            old_name='Written_permission_from_the_site_owner_and_gathering_of_materials',
            new_name='Written_permission_from_the_owner_and_gathering_of_materials',
        ),
    ]
