# Generated by Django 3.1 on 2022-09-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Login', '0024_rename_written_permission_from_the_site_owner_and_gathering_of_materials_school_profile_written_perm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school_profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
