# Generated by Django 3.2.7 on 2022-04-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0002_auto_20220426_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks_of_user',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='marks_of_user',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Marks_Of_User',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
