# Generated by Django 3.2.7 on 2022-05-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Index', '0003_auto_20220426_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo1', models.ImageField(upload_to='')),
                ('logo2', models.ImageField(upload_to='Exhibition')),
                ('image1', models.ImageField(upload_to='Exhibition')),
                ('image2', models.ImageField(upload_to='Exhibition')),
                ('image3', models.ImageField(upload_to='Exhibition')),
                ('image4', models.ImageField(upload_to='Exhibition')),
                ('image5', models.ImageField(upload_to='Exhibition')),
                ('video', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
