# Generated by Django 3.2.7 on 2022-05-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0005_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='logo1',
            field=models.ImageField(upload_to='Exhibition'),
        ),
    ]
