# Generated by Django 3.2.7 on 2022-05-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0007_preview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Preview',
        ),
    ]
