# Generated by Django 4.0.1 on 2022-08-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0009_contactform_contactlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Task1')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
