# Generated by Django 4.0.1 on 2022-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0010_task1_delete_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='image',
        ),
        migrations.AddField(
            model_name='task1',
            name='image1',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AddField(
            model_name='task1',
            name='image2',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AddField(
            model_name='task1',
            name='image3',
            field=models.ImageField(blank=True, upload_to='Task1'),
        ),
        migrations.AddField(
            model_name='task1',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
    ]
