# Generated by Django 4.0.1 on 2022-08-29 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Index', '0011_remove_task1_image_task1_image1_task1_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='name',
        ),
        migrations.AddField(
            model_name='task1',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
