# Generated by Django 4.0.1 on 2022-08-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0012_remove_task1_name_task1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='user',
        ),
    ]
