# Generated by Django 4.0.1 on 2022-08-30 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0014_task1_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task1',
        ),
    ]
