# Generated by Django 3.1 on 2022-09-29 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0016_auto_20220929_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribe',
            new_name='subscriber',
        ),
    ]
